import { PT_Sans } from 'next/font/google';
import './components/globals.css';
import Header from './components/Header';

const ptSans = PT_Sans({
	subsets: ['latin'],
	weight: ['400', '700'],
});

// const bloggerSans = BloggerSans({
//   subsets: ['latin'],
//   weight: ['400', '700']
// })

export const metadata = {
	title: 'Hands of Friends',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='uk-UA'>
			<body className={ptSans.className}>
				<Header />
				<main className='mx-auto max-w-7xl'>{children}</main>
			</body>
		</html>
	);
}
